#!/data/data/com.termux/files/usr/bin/bash


## for enabling https://amaitlab.guthub.io/ repository
## Author : amsit <dezavue3@gmail.com>
## 

set -e

## Ensure PREFIX
test -z $PREFIX && \
	PREFIX=/data/data/com.termux/files/usr

## Ensure TMPDIR
test -z $TMPDIR && \
	TMPDIR="${PREFIX}/tmp"

## gnupg public key file
PUBKEY="${TMPDIR}/pubkey.gpg"
## user device architecture
ARCHITECTURE=$(uname -m)
## location of sources.list
SOURCES_LIST="${PREFIX}/etc/apt/sources.list.d/amsitlab.list"


## main program
main(){

## Displaying help message when args count is 0
if [ $# -eq 0 ]; then
	__help 
	exit
fi


## Filtering allowed arg 1
## Display help message when arg 1 is invalid.
case $1 in 
	"enable"|"disable")
		$@
		apt update
		;;
	"-h"|"help"|*)
		__help
		;;
esac


}

## help message
__help(){

	echo "Usage: "
	echo
	echo "	amsitlab-repo enable"
	echo "		enabling repo https://amsitlab.github.io"
	echo
	echo "	amsitlab-repo disable"
	echo "		disabling repo https://amsitlab.github.io"
	echo
	echo "	amsitlab-repo help"
	echo "		show this message and exit"
	echo 
	echo 
	echo "# 2018 (C) amsitlab"

}

## help message
help(){
	## redirect 
	__help
}

__missing () {
	if [ "x`which ${PREFIX}/bin/${2}`" == "x" ]; then
		apt install -y $1
	fi	
}

## enabling repository
enable(){
apt update
apt upgrade -y


echo "Enabaling"
#apt install gnupg wget
__missing "curl" "curl"

## Download gnupg public key
curl -# -L "https://amsitlab.github.io/pubkey.gpg" -o "$PUBKEY"

apt-key add "$PUBKEY"

rm -fr "$PUBKEY"

## Prevent duplicate entries in sources.list
disable

## Ensure user device architecture
## set as "aarch64" when architecture unknown
if [ -z "$ARCHITECTURE" ]; then
	echo "Unknown architecture"
	echo "Note:"
	echo "	Architecture will be set as \"aarch64\""
	echo "	If this wrong, Please edit file"
	echo "	${SOURCES_LIST/$HOME/\~}"
	ARCHITECTURE=aarch64
fi

## do not ask me , you known it
case "$ARCHITECTURE" in
	armv7*)
		ARCHITECTURE=arm
		;;
esac

	[ ! -r "$SOURCES_LIST" ] && {
		echo "deb [trusted=true,arch=all,${ARCHITECTURE}] https://amsitlab.github.io/ termux amsitlab" > "$SOURCES_LIST"
	}


}


## Disabling repo
disable(){
	#sed -i '/https:\/\/amsitlab.github.io\//d' "$SOURCES_LIST"
	rm -f $SOURCES_LIST
}

main $@

unset SOURCES_LIST ARCHITECTURE PUBKEY
